#file: noinspection SpringBootApplicationYaml
server:
  port: 8888
  tomcat:
    threads:
      max: 200        # 设定处理客户请求的线程的最大数目，决定了服务器可以同时响应客户请求的数,默认200
      min-spare: 50   # 初始化线程数,最小空闲线程数,默认是10
    accept-count: 10  # 等待队列长度
  servlet:
    context-path: /api/${app.config.api-version}

# 应用配置 app.config.api-version
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy


spring:
  # 数据库配置
  datasource:
    host: 127.0.0.1
    port: 16379
    databaseName:
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.databaseName}?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=false
    username: root
    password: lijiaqiang12@
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    pool-name: Retail_HikariCP
    minimum-idle: 15 #最小空闲连接数量
    idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
    maximum-pool-size: 25 #连接池最大连接数，默认是10
    auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
    max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
    connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
    connection-test-query: SELECT 1
  type: com.zaxxer.hikari.HikariDataSource

  # Spring 配置；rabbitmq
  rabbitmq:
    addresses: 127.0.0.1
    port: 15432
    username: jasonlat
    password: lijiaqiang12@
    listener:
      simple:
        prefetch: 1 # 每次投递n个消息，消费完在投递n个
    topic:
      activity_sku_stock_zero: activity_sku_stock_zero


# mybatis plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/*.xml

jq1024:
  cc:
    # redisson 配置
    redisson:
      host: 127.0.0.1
      port: 16379
      password: lijiaqiang12@
      database: 0
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true
    # jwt token 配置
    jwt:
      issuer: ccf@guida_ljq_pwb
      ttl: 86_400_000
      secret-key: ccf@guida_ljq_pwb

  # 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml